### ISSUE TITLE
Request: Handle atom error messages

### ISSUE THREAD

**Issue by ACBullen** [mirego/absinthe_error_payload#10]
Is there any intent/interest in accepting atoms as error messages? For instance if the reason a mutation errors is its unauthenticated or the record it is attempting to change doesn't exist, `:unauthorized` or `:not_found` would be the expected error return, but if I want this library to parse that into the message I'd have to check to see if I'm returning an atom everywhere I might and stringify it.

Is adding a function head that converts atoms to binaries to `convert_to_payload/1` a reasonable thing, or is the assumption that users of this library catch simple atom errors and format them into more verbose errors?

**Comment by ACBullen** [comment]
Made a quick implementation in [this PR](https://github.com/mirego/absinthe_error_payload/pull/12)

**Comment by ACBullen** [comment]
Any opinions from the maintainers on this request and the related PR?

**Comment by remi** [comment]
This as closed by #12 👌
