### ISSUE TITLE
Middleware style usage example/tutorial

### ISSUE THREAD

**Issue by JosipSylo** [mirego/absinthe_error_payload#15]
Are there any projects using this library that I could check out?
When I follow the docs https://hexdocs.pm/absinthe_error_payload/AbsintheErrorPayload.Payload.html#module-usage, I keep getting errors and I can't figure out why. Thanks 😄 

This is the error I get btw
`
Unexpected validation message: #Ecto.Changeset<action: :insert, changes: %{email: \"vxasaaa\", password_hash: \"P\", role: \"d\", username: \"hadfsaaaa\"}, errors: [username: {\"has already been taken\", [constraint: :unique, constraint_name: \"users_username_index\"]}]
`

**Comment by rwngallego** [comment]
Same issue here

**Comment by JosipSylo** [comment]
It seems to be fixed in 1.1.2. Thank you
